### ISSUE TITLE
Downloading maps doesn't work anymore

### ISSUE THREAD

**Issue by Schraubstock** [viking-gps/viking#100] opened 2020-07-13 17:19 UTC
Downloading maps (even those predefined like Bing, Terraserver, OSM, BlueMarble) doesn't work anymore since a couple of weeks, even though I didn't change anything.
Some years ago, I managed to add OpenHikingMap and some others to the selectable maps and found out, that OpenTopoMap.org wouldn't work due to httpS. But I am absolutely puzzled why now ALL my maps won't download tiles anymore and I can only use a bunch of tiles from the cache.
Does anyone know about discontinued support or has experienced the same issue?

**Comment by rnorris** [comment] 2020-07-13 19:59
What is your OS and Viking version?

There have been some previous issues with using/specifying https sources.

See at least https://sourceforge.net/p/viking/bugs/149/ 

NB Terraserver has not been available for many years; OSM and BlueMarble is working for me (latest head code in repository but shouldn't be different in regards to maps from v1.8)

**Comment by Schraubstock** [comment] 2020-07-14 10:55
Versions are kubuntu 14.04 and viking 1.4.2

As I wrote, I know about the https-issue, but those predefined and my other http-sources (non-httpS) worked for years and suddenly without any change.
BlueMarble and OSM (MapQuest) are working on a global/continental zoom level, OSM (Mapnik) seems to be working properly and OSM (Cycle) is working properly except for "API Key Required" written over the tiles...

I just put your snippet from 2018-01-08 into my maps.XML (https://sourceforge.net/p/viking/bugs/149/#f5ff)
And this loads OpenStreetMaps-Data but not OpenTopoMap-Data... mighty strange...

**Comment by rnorris** [comment] 2020-07-14 17:53
You may want to try running Viking from the command line with the options -Vd to trace more about what is happening.

It's possible that the web services have added additional redirects which now exceeds the download attempt limit.
IIRC older Viking versions either defaulted to not following redirects or the value was quite small.
Setting/increasing this value may help for your other map sources, e.g. adding:

     <property name="follow-location">5</property>

**Comment by Schraubstock** [comment] 2020-07-25 14:45
With OpenHikingMap.org selected, "viking -Vd" says something like:
`< HTTP/1.1 301 Moved Permanently
< Date: Sat, 25 Jul 2020 14:38:55 GMT
* Server Apache/2.4.38 (Debian) is not blacklisted
< Server: Apache/2.4.38 (Debian)
< Location: https://maps.refuges.info/hiking/13/4460/2751.png
< Content-Length: 340
< Content-Type: text/html; charset=iso-8859-1
< 
* Connection #4 to host maps.refuges.info left intact

** (viking:8841): WARNING **: curl_download_uri: http response: 301 for uri http://maps.refuges.info/hiking/13/4460/2751.png

** (viking): DEBUG: download: download failed: curl_download_get_url=2

** (viking:8841): WARNING **: Fehler beim Herunterladen: /home/nobbert/.viking-maps/t1001s4z0/4460/2751
** (viking): DEBUG: curl_download_uri: uri=http://maps.refuges.info/hiking/13/4460/2752.png
* Found bundle for host maps.refuges.info: 0x7f585c014430
* Re-using existing connection! (#4) with host maps.refuges.info
* Connected to maps.refuges.info (62.210.104.149) port 80 (#4)
> GET /hiking/13/4460/2752.png HTTP/1.1
User-Agent: viking/1.4.2 libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3
Host: maps.refuges.info
Accept: */*

< HTTP/1.1 301 Moved Permanently
< Date: Sat, 25 Jul 2020 14:38:55 GMT
* Server Apache/2.4.38 (Debian) is not blacklisted
< Server: Apache/2.4.38 (Debian)
< Location: https://maps.refuges.info/hiking/13/4460/2752.png
< Content-Length: 340
< Content-Type: text/html; charset=iso-8859-1
< 
* Connection #4 to host maps.refuges.info left intact

** (viking:8841): WARNING **: curl_download_uri: http response: 301 for uri http://maps.refuges.info/hiking/13/4460/2752.png

** (viking): DEBUG: download: download failed: curl_download_get_url=2

** (viking:8841): WARNING **: Fehler beim Herunterladen: /home/nobbert/.viking-maps/t1001s4z0/4460/2752`

With your suggested "follow-location 5" added it says:
`< HTTP/1.1 301 Moved Permanently
< Date: Sat, 25 Jul 2020 14:44:16 GMT
* Server Apache/2.4.38 (Debian) is not blacklisted
< Server: Apache/2.4.38 (Debian)
< Location: https://maps.refuges.info/hiking/17/69542/46161.png
< Content-Length: 342
< Content-Type: text/html; charset=iso-8859-1
< 
* Ignoring the response-body
* Connection #379 to host maps.refuges.info left intact
* Issue another request to this URL: 'https://maps.refuges.info/hiking/17/69542/46161.png'
* Found bundle for host maps.refuges.info: 0x7f11a8014f20
* Hostname was found in DNS cache
*   Trying 62.210.104.149...
* Connected to maps.refuges.info (62.210.104.149) port 443 (#390)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 390
** (viking): DEBUG: download: download failed: curl_download_get_url=2

** (viking:9408): WARNING **: Fehler beim Herunterladen: /home/nobbert/.viking-maps/t1001s0z0/69542/46161
** (viking): DEBUG: curl_download_uri: uri=http://maps.refuges.info/hiking/17/69542/46162.png
* Found bundle for host maps.refuges.info: 0x7f11a8014f20
* Re-using existing connection! (#379) with host maps.refuges.info
* Connected to maps.refuges.info (62.210.104.149) port 80 (#379)
> GET /hiking/17/69542/46162.png HTTP/1.1
User-Agent: viking/1.4.2 libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3
Host: maps.refuges.info
Accept: */*

< HTTP/1.1 301 Moved Permanently
< Date: Sat, 25 Jul 2020 14:44:17 GMT
* Server Apache/2.4.38 (Debian) is not blacklisted
< Server: Apache/2.4.38 (Debian)
< Location: https://maps.refuges.info/hiking/17/69542/46162.png
< Content-Length: 342
< Content-Type: text/html; charset=iso-8859-1
< 
* Ignoring the response-body
* Connection #379 to host maps.refuges.info left intact
* Issue another request to this URL: 'https://maps.refuges.info/hiking/17/69542/46162.png'
* Found bundle for host maps.refuges.info: 0x7f11a8014f20
* Hostname was found in DNS cache
*   Trying 62.210.104.149...
* Connected to maps.refuges.info (62.210.104.149) port 443 (#391)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 391
** (viking): DEBUG: download: download failed: curl_download_get_url=2

** (viking:9408): WARNING **: Fehler beim Herunterladen: /home/nobbert/.viking-maps/t1001s0z0/69542/46162`

**Comment by rnorris** [comment] 2020-08-02 12:38
The issue appears to be this:

**server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none**

Presumably an equivalent command line effort will also fail (or put error text into the output file):

    curl -Lv http://maps.refuges.info/hiking/17/69542/46162.png -o 46162.png

It seems your SSL certificate store is now out of date, since your OS is quite old and presumably no further automatic updates for this are available.

I'm afraid you'll have to investigate "ubuntu ca-certificates.crt" with your favourite search engine and possibly update the certificate store manually. This is out of scope of Viking's remit.

**Comment by rnorris** [comment] 2020-08-03 19:31
Forgot to mention that part of the issue is Viking doesn't expose this information in the GUI, to make it easier for the user to troubleshoot issues.
ATM the result of the downloading request is converted into a simple either it worked or failed.
Some of the detail could be captured and exposed somehow...

**Comment by rnorris** [comment] 2020-09-10 21:42
I've now made the log accessible in the GUI and also possible to enable extra debug output from the GUI so it more easy for the user to diagnose potential configuration issues and other sources of unexpected behaviour.

**Closed by rnorris** 2020-09-10 21:42 UTC
