### ISSUE TITLE
Error : entry point ScriptIsComplex... in GDI32.dll Windows 7

### ISSUE THREAD

**Issue by McAsulys** [viking-gps/viking#136] opened 2021-08-27 20:40 UTC
Hi, i try to install viking on my Windows 7 and got issue with an entry point ScriptIsComplex that coud not be located the GDI32 DLL. I try update it manually but my windows crash at startup. So i guess windows 7 is not abable to run Vinking. Is theyr way to make it run on win7 ? 

That by advance.

**Comment by rnorris** [comment] 2021-09-11 19:27
This seems to be this problem:

https://docs.microsoft.com/en-us/windows/win32/api/usp10/nf-usp10-scriptiscomplex#remarks

Unfortunately I don't readily have access to a Windows 7 64bit system, so I can't test my provisional changes to the build. However I've made preview release on dropbox here:

https://www.dropbox.com/s/5hshac2hxnmg6le/viking-win64-1.9.0.0.exe?dl=0

So it would be great if you @McAsulys could confirm if this does indeed fix it.

**Comment by McAsulys** [comment] 2021-09-12 15:11
Thanks, but still the same issue. I try to use the latest version of
the DLL, but that make my system crash. Si theyr is method or fonction
used by Vinking that's not supported by Win7. Btw it work fine on my
linux.


2021-09-11 21:27 UTC+02:00, Rob Norris ***@***.***>:

**Comment by rnorris** [comment] 2021-09-13 20:38
It's not Viking itself, but one (or more) of the dependencies (I haven't spent any time trying to identify which ones) used by Viking.

However it seems it has a knock effort to the build of Viking on Windows.

I'll see if I can get hold of a Windows 7 64 bit system, but since Windows 7 is of course very much End of Life - I ultimately won't be putting too much effort into fixing it.

**Comment by McAsulys** [comment] 2021-09-14 02:06
Thanks, if you find a

2021-09-13 22:38 UTC+02:00, Rob Norris ***@***.***>:

**Comment by McAsulys** [comment] 2021-09-14 02:07
Oupse, so, i was saying : Thanks. If you find a solution, tell me, but
don't worry if their's any, i'll use Viking on my linux.

Have a nice day.

2021-09-14 4:06 UTC+02:00, Benedict Dourlens ***@***.***>:

**Comment by rnorris** [comment] 2021-09-17 17:08
Update: I've discovered the component that is using ScriptIsComplex - which is __libpangowin32-1.0-0.dll__

The DLL used in Viking is prebuilt from 
https://build.opensuse.org/package/view_file/windows:mingw:win64/mingw64-pango/

Which is using a 6 year old release - 1.38, whereas the latest upstream is 1.49 see https://pango.gnome.org/
I'm not even sure where to raise the issue.

I may be able to build libpangowin32-1.0-0.dll myself and package that with Viking.

**Comment by McAsulys** [comment] 2021-09-17 17:14
Great news, i'm waiting for the build to test it and give you review
about it. Thanks.

2021-09-17 19:08 UTC+02:00, Rob Norris ***@***.***>:

**Comment by rnorris** [comment] 2021-09-19 14:05
Seems like pango since version v1.42.2 has carried a fix for this issue.
https://bugzilla.gnome.org/show_bug.cgi?id=795045#c0

So I've backported the fix into the 1.38.1 version and included this libpangowin32-1.0-0.dll into the Viking build.
This is still OK under Windows 10.

An updated preview release is on dropbox - to confirm if it still works under Windows 7: 

https://www.dropbox.com/s/dol48wa2n2z2nt4/viking-win64-1.9.0.0.exe?dl=0

**Comment by rnorris** [comment] 2021-09-28 21:54
I have created a Windows 7 64 VM and confirmed the above fix does indeed work.

**Closed** 2021-09-28 22:58 UTC
